# Production environment override
services:
  php:
    build:
      target: app_php
    environment:
      APP_ENV: prod
  nginx:
    volumes:
      - ./docker/nginx/templates/prod.site.conf.template:/etc/nginx/templates/site.conf.template
    ports:
      - "${NGINX_PORT:-8000}:80"
      - "${NGINX_PORT_SSL:-8043}:443"
