parameters:
    app.base_roles:
        - 'ROLE_USER'
        - 'ROLE_EDITOR'
        - 'ROLE_ADMIN'
    app.specialist_roles:
        - 'ROLE_ANTHROPOLOGIST'
        - 'ROLE_ARCHAEOBOTANIST'
        - 'ROLE_CERAMIC_SPECIALIST'
        - 'ROLE_GEO_ARCHAEOLOGIST'
        - 'ROLE_HISTORIAN'
        - 'ROLE_MATERIAL_ANALYST'
        - 'ROLE_PALEOCLIMATOLOGIST'
        - 'ROLE_ZOO_ARCHAEOLOGIST'

