<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250621090503 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA vocabulary');
        $this->addSql('CREATE SCHEMA auth');
        $this->addSql('CREATE SEQUENCE analyses_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE analysis_join_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE analysis_context_zoo_taxonomies_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vocabulary.analysis_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE context_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vocabulary.context_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vocabulary.decoration_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE individuals_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE media_object_join_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vocabulary.media_object_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE media_objects_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mus_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE potteries_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pottery_decorations_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vocabulary.pottery_functional_forms_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vocabulary.pottery_functional_groups_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vocabulary.pottery_shapes_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE sample_stratigraphic_units_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vocabulary.sample_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE site_cultural_contexts_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE stratigraphic_units_relationships_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vocabulary.surface_treatment_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vocabulary.zoo_bone_parts_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE zoo_bone_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vocabulary.zoo_bones_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vocabulary.zoo_taxonomy_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE analyses (id BIGINT NOT NULL, identifier VARCHAR(255) NOT NULL, status SMALLINT NOT NULL, responsible VARCHAR(255) DEFAULT NULL, summary TEXT DEFAULT NULL, analysis_type_id SMALLINT NOT NULL, created_by_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC86883CBF9DEA95 ON analyses (analysis_type_id)');
        $this->addSql('CREATE INDEX IDX_AC86883CB03A8386 ON analyses (created_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AC86883C772E836A ON analyses (identifier)');
        $this->addSql('CREATE TABLE analyses_microstratigraphic_units (summary TEXT DEFAULT NULL, id BIGINT NOT NULL, analysis_id BIGINT NOT NULL, subject_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1A1A0B527941003F ON analyses_microstratigraphic_units (analysis_id)');
        $this->addSql('CREATE INDEX IDX_1A1A0B5223EDC87 ON analyses_microstratigraphic_units (subject_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1A1A0B5223EDC877941003F ON analyses_microstratigraphic_units (subject_id, analysis_id)');
        $this->addSql('CREATE TABLE analysis_context_zoo_taxonomies (id BIGINT NOT NULL, analysis_id BIGINT NOT NULL, taxonomy_id SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_87214BDC7941003F ON analysis_context_zoo_taxonomies (analysis_id)');
        $this->addSql('CREATE INDEX IDX_87214BDC9557E6F6 ON analysis_context_zoo_taxonomies (taxonomy_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_87214BDC7941003F9557E6F6 ON analysis_context_zoo_taxonomies (analysis_id, taxonomy_id)');
        $this->addSql('CREATE TABLE analysis_context_zoos (summary TEXT DEFAULT NULL, id BIGINT NOT NULL, analysis_id BIGINT NOT NULL, subject_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4CDE93227941003F ON analysis_context_zoos (analysis_id)');
        $this->addSql('CREATE INDEX IDX_4CDE932223EDC87 ON analysis_context_zoos (subject_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4CDE932223EDC877941003F ON analysis_context_zoos (subject_id, analysis_id)');
        $this->addSql('CREATE TABLE analysis_potteries (summary TEXT DEFAULT NULL, id BIGINT NOT NULL, analysis_id BIGINT NOT NULL, subject_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_631A18587941003F ON analysis_potteries (analysis_id)');
        $this->addSql('CREATE INDEX IDX_631A185823EDC87 ON analysis_potteries (subject_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_631A185823EDC877941003F ON analysis_potteries (subject_id, analysis_id)');
        $this->addSql('CREATE TABLE vocabulary.analysis_types (id SMALLINT NOT NULL, code VARCHAR(255) NOT NULL, type_group VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4614CD7663CCC3321D775834 ON vocabulary.analysis_types (type_group, value)');
        $this->addSql('CREATE TABLE analysis_zoo_bones (summary TEXT DEFAULT NULL, id BIGINT NOT NULL, analysis_id BIGINT NOT NULL, subject_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EB9AEAD07941003F ON analysis_zoo_bones (analysis_id)');
        $this->addSql('CREATE INDEX IDX_EB9AEAD023EDC87 ON analysis_zoo_bones (subject_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB9AEAD023EDC877941003F ON analysis_zoo_bones (subject_id, analysis_id)');
        $this->addSql('CREATE TABLE analysis_zoo_teeth (summary TEXT DEFAULT NULL, id BIGINT NOT NULL, analysis_id BIGINT NOT NULL, subject_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BE6E6D8B7941003F ON analysis_zoo_teeth (analysis_id)');
        $this->addSql('CREATE INDEX IDX_BE6E6D8B23EDC87 ON analysis_zoo_teeth (subject_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BE6E6D8B23EDC877941003F ON analysis_zoo_teeth (subject_id, analysis_id)');
        $this->addSql('CREATE TABLE context_stratigraphic_units (id BIGINT NOT NULL, su_id BIGINT NOT NULL, context_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A2BE5B62BDB1218E ON context_stratigraphic_units (su_id)');
        $this->addSql('CREATE INDEX IDX_A2BE5B626B00C1CF ON context_stratigraphic_units (context_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2BE5B62BDB1218E6B00C1CF ON context_stratigraphic_units (su_id, context_id)');
        $this->addSql('CREATE TABLE vocabulary.context_types (id SMALLINT NOT NULL, type_group VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C753887663CCC3321D775834 ON vocabulary.context_types (type_group, value)');
        $this->addSql('CREATE TABLE contexts (id BIGINT NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type_id SMALLINT NOT NULL, site_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC51CEB5C54C8C93 ON contexts (type_id)');
        $this->addSql('CREATE INDEX IDX_AC51CEB5F6BD1646 ON contexts (site_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AC51CEB5F6BD1646C54C8C935E237E06 ON contexts (site_id, type_id, name)');
        $this->addSql('CREATE TABLE vocabulary.cultural_contexts (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DC0C4A0E1D775834 ON vocabulary.cultural_contexts (value)');
        $this->addSql('CREATE TABLE vocabulary.decoration (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4B9C50A41D775834 ON vocabulary.decoration (value)');
        $this->addSql('CREATE TABLE vocabulary.individual_ages (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D29ED9621D775834 ON vocabulary.individual_ages (value)');
        $this->addSql('CREATE TABLE individuals (id BIGINT NOT NULL, identifier VARCHAR(255) NOT NULL, sex CHAR(1) DEFAULT NULL, notes TEXT DEFAULT NULL, site_id BIGINT NOT NULL, age_id SMALLINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_985AD930F6BD1646 ON individuals (site_id)');
        $this->addSql('CREATE INDEX IDX_985AD930CC80CD12 ON individuals (age_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_985AD930772E836A ON individuals (identifier)');
        $this->addSql('COMMENT ON COLUMN individuals.sex IS \'F = female, M = male, ? = indeterminate\'');
        $this->addSql('CREATE TABLE media_object_analyses (description TEXT DEFAULT NULL, id BIGINT NOT NULL, media_object_id BIGINT NOT NULL, item_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C2D113064DE5A5 ON media_object_analyses (media_object_id)');
        $this->addSql('CREATE INDEX IDX_C2D1130126F525E ON media_object_analyses (item_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C2D1130126F525E64DE5A5 ON media_object_analyses (item_id, media_object_id)');
        $this->addSql('CREATE TABLE media_object_stratigraphic_units (description TEXT DEFAULT NULL, id BIGINT NOT NULL, media_object_id BIGINT NOT NULL, item_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2DAB12CC64DE5A5 ON media_object_stratigraphic_units (media_object_id)');
        $this->addSql('CREATE INDEX IDX_2DAB12CC126F525E ON media_object_stratigraphic_units (item_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DAB12CC126F525E64DE5A5 ON media_object_stratigraphic_units (item_id, media_object_id)');
        $this->addSql('CREATE TABLE vocabulary.media_object_types (id SMALLINT NOT NULL, type_group VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F365A0CA63CCC3321D775834 ON vocabulary.media_object_types (type_group, value)');
        $this->addSql('CREATE TABLE media_objects (id BIGINT NOT NULL, file_path VARCHAR(255) NOT NULL, original_filename VARCHAR(255) NOT NULL, sha256 CHAR(64) NOT NULL, mime_type VARCHAR(255) NOT NULL, size INT NOT NULL, width SMALLINT DEFAULT NULL, height SMALLINT DEFAULT NULL, upload_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, description TEXT DEFAULT NULL, type_id SMALLINT NOT NULL, uploaded_by_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D3CD4ABA5CC814F7 ON media_objects (sha256)');
        $this->addSql('CREATE INDEX IDX_D3CD4ABAC54C8C93 ON media_objects (type_id)');
        $this->addSql('CREATE INDEX IDX_D3CD4ABAA2B28FE8 ON media_objects (uploaded_by_id)');
        $this->addSql('CREATE TABLE mus (id BIGINT NOT NULL, identifier VARCHAR(255) NOT NULL, notes TEXT DEFAULT NULL, stratigraphic_unit_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_240A2C54A502ADE ON mus (stratigraphic_unit_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_240A2C54A502ADE772E836A ON mus (stratigraphic_unit_id, identifier)');
        $this->addSql('CREATE TABLE potteries (id BIGINT NOT NULL, inventory VARCHAR(255) NOT NULL, inner_color VARCHAR(255) DEFAULT NULL, outer_color VARCHAR(255) DEFAULT NULL, decoration_motif VARCHAR(255) DEFAULT NULL, chronology_lower INT DEFAULT NULL, chronology_upper INT DEFAULT NULL, notes TEXT DEFAULT NULL, stratigraphic_unit_id BIGINT NOT NULL, surface_treatment_id SMALLINT DEFAULT NULL, cultural_context_id SMALLINT DEFAULT NULL, part_id SMALLINT DEFAULT NULL, functional_group_id SMALLINT NOT NULL, functional_form_id SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_91910162B12D4A36 ON potteries (inventory)');
        $this->addSql('CREATE INDEX IDX_91910162A502ADE ON potteries (stratigraphic_unit_id)');
        $this->addSql('CREATE INDEX IDX_91910162EFB04BBB ON potteries (surface_treatment_id)');
        $this->addSql('CREATE INDEX IDX_9191016271C15152 ON potteries (cultural_context_id)');
        $this->addSql('CREATE INDEX IDX_919101624CE34BEC ON potteries (part_id)');
        $this->addSql('CREATE INDEX IDX_919101629D56156 ON potteries (functional_group_id)');
        $this->addSql('CREATE INDEX IDX_91910162BC19D7E9 ON potteries (functional_form_id)');
        $this->addSql('CREATE TABLE pottery_decorations (id BIGINT NOT NULL, pottery_id BIGINT NOT NULL, decoration_id SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9E9301E3F23816BB ON pottery_decorations (pottery_id)');
        $this->addSql('CREATE INDEX IDX_9E9301E33446DFC4 ON pottery_decorations (decoration_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9E9301E3F23816BB3446DFC4 ON pottery_decorations (pottery_id, decoration_id)');
        $this->addSql('CREATE TABLE vocabulary.pottery_functional_forms (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_703164D21D775834 ON vocabulary.pottery_functional_forms (value)');
        $this->addSql('CREATE TABLE vocabulary.pottery_functional_groups (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BBE4E3481D775834 ON vocabulary.pottery_functional_groups (value)');
        $this->addSql('CREATE TABLE vocabulary.pottery_shapes (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE2DA1D31D775834 ON vocabulary.pottery_shapes (value)');
        $this->addSql('CREATE TABLE auth.refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_39BB651DC74F2195 ON auth.refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE sample_stratigraphic_units (id BIGINT NOT NULL, sample_id BIGINT NOT NULL, su_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1A344B061B1FEA20 ON sample_stratigraphic_units (sample_id)');
        $this->addSql('CREATE INDEX IDX_1A344B06BDB1218E ON sample_stratigraphic_units (su_id)');
        $this->addSql('CREATE TABLE vocabulary.sample_types (id SMALLINT NOT NULL, code VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F19230977153098 ON vocabulary.sample_types (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F1923091D775834 ON vocabulary.sample_types (value)');
        $this->addSql('CREATE TABLE samples (id BIGINT NOT NULL, year SMALLINT NOT NULL, number SMALLINT NOT NULL, description TEXT DEFAULT NULL, site_id BIGINT NOT NULL, type_id SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_19925777F6BD1646 ON samples (site_id)');
        $this->addSql('CREATE INDEX IDX_19925777C54C8C93 ON samples (type_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_19925777F6BD1646C54C8C93BB82733796901F54 ON samples (site_id, type_id, year, number)');
        $this->addSql('CREATE TABLE site_cultural_contexts (id BIGINT NOT NULL, site_id BIGINT NOT NULL, cultural_context_id SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_35F57A8EF6BD1646 ON site_cultural_contexts (site_id)');
        $this->addSql('CREATE INDEX IDX_35F57A8E71C15152 ON site_cultural_contexts (cultural_context_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_35F57A8EF6BD164671C15152 ON site_cultural_contexts (site_id, cultural_context_id)');
        $this->addSql('CREATE TABLE auth.site_user_privileges (id UUID NOT NULL, privilege INT NOT NULL, user_id UUID NOT NULL, site_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7FEC3DADA76ED395 ON auth.site_user_privileges (user_id)');
        $this->addSql('CREATE INDEX IDX_7FEC3DADF6BD1646 ON auth.site_user_privileges (site_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7FEC3DADA76ED395F6BD1646 ON auth.site_user_privileges (user_id, site_id)');
        $this->addSql('CREATE TABLE sites (id BIGINT NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, chronology_lower SMALLINT DEFAULT NULL, chronology_upper SMALLINT DEFAULT NULL, field_director VARCHAR(255) DEFAULT NULL, created_by_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BC00AA6377153098 ON sites (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BC00AA635E237E06 ON sites (name)');
        $this->addSql('CREATE INDEX IDX_BC00AA63B03A8386 ON sites (created_by_id)');
        $this->addSql('CREATE TABLE stratigraphic_units_relationships (id BIGINT NOT NULL, lft_su_id BIGINT NOT NULL, relationship_id CHAR(1) NOT NULL, rgt_su_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_14B3FD8DD4B657AB ON stratigraphic_units_relationships (lft_su_id)');
        $this->addSql('CREATE INDEX IDX_14B3FD8D2C41D668 ON stratigraphic_units_relationships (relationship_id)');
        $this->addSql('CREATE INDEX IDX_14B3FD8D7C1ECED6 ON stratigraphic_units_relationships (rgt_su_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_14B3FD8DD4B657AB7C1ECED6 ON stratigraphic_units_relationships (lft_su_id, rgt_su_id)');
        $this->addSql('CREATE TABLE vocabulary.su_relationships (id CHAR(1) NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, inverted_by_id CHAR(1) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_319E6DFF1D775834 ON vocabulary.su_relationships (value)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_319E6DFFC4CDAD40 ON vocabulary.su_relationships (inverted_by_id)');
        $this->addSql('CREATE TABLE vocabulary.surface_treatment (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2F1E3C0A1D775834 ON vocabulary.surface_treatment (value)');
        $this->addSql('CREATE TABLE sus (id BIGINT NOT NULL, year INT NOT NULL, number INT NOT NULL, description TEXT DEFAULT NULL, interpretation TEXT DEFAULT NULL, site_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_32B2A22EF6BD1646 ON sus (site_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_32B2A22EF6BD1646BB82733796901F54 ON sus (site_id, year, number)');
        $this->addSql('CREATE TABLE auth.users (id UUID NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_18DF2AF8E7927C74 ON auth.users (email)');
        $this->addSql('CREATE TABLE vocabulary.zoo_bone_parts (id SMALLINT NOT NULL, code VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_41B0A82877153098 ON vocabulary.zoo_bone_parts (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_41B0A8281D775834 ON vocabulary.zoo_bone_parts (value)');
        $this->addSql('CREATE TABLE zoo_bones (id BIGINT NOT NULL, ends_preserved SMALLINT DEFAULT NULL, side CHAR(1) DEFAULT NULL, notes VARCHAR(255) DEFAULT NULL, stratigraphic_unit_id BIGINT NOT NULL, voc_taxonomy_id SMALLINT DEFAULT NULL, voc_bone_id SMALLINT DEFAULT NULL, voc_bone_part_id SMALLINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1911F3EAA502ADE ON zoo_bones (stratigraphic_unit_id)');
        $this->addSql('CREATE INDEX IDX_1911F3EA2A3A1291 ON zoo_bones (voc_taxonomy_id)');
        $this->addSql('CREATE INDEX IDX_1911F3EAE26518D6 ON zoo_bones (voc_bone_id)');
        $this->addSql('CREATE INDEX IDX_1911F3EA2BAA4AD9 ON zoo_bones (voc_bone_part_id)');
        $this->addSql('COMMENT ON COLUMN zoo_bones.side IS \'L = left, R = right, ? = indeterminate\'');
        $this->addSql('CREATE TABLE vocabulary.zoo_bones (id SMALLINT NOT NULL, code VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88CCAECB77153098 ON vocabulary.zoo_bones (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88CCAECB1D775834 ON vocabulary.zoo_bones (value)');
        $this->addSql('CREATE TABLE vocabulary.zoo_taxonomy (id SMALLINT NOT NULL, code VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, vernacular_name VARCHAR(255) NOT NULL, class VARCHAR(255) NOT NULL, family VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD4BDA3C77153098 ON vocabulary.zoo_taxonomy (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD4BDA3C1D775834 ON vocabulary.zoo_taxonomy (value)');
        $this->addSql('CREATE TABLE zoo_teeth (id BIGINT NOT NULL, connected BOOLEAN NOT NULL, side CHAR(1) DEFAULT NULL, notes VARCHAR(255) DEFAULT NULL, stratigraphic_unit_id BIGINT NOT NULL, voc_taxonomy_id SMALLINT DEFAULT NULL, voc_tooth_id SMALLINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4CE574B1A502ADE ON zoo_teeth (stratigraphic_unit_id)');
        $this->addSql('CREATE INDEX IDX_4CE574B12A3A1291 ON zoo_teeth (voc_taxonomy_id)');
        $this->addSql('CREATE INDEX IDX_4CE574B123332A79 ON zoo_teeth (voc_tooth_id)');
        $this->addSql('COMMENT ON COLUMN zoo_teeth.side IS \'L = left, R = right, ? = indeterminate\'');
        $this->addSql('ALTER TABLE analyses ADD CONSTRAINT FK_AC86883CBF9DEA95 FOREIGN KEY (analysis_type_id) REFERENCES vocabulary.analysis_types (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analyses ADD CONSTRAINT FK_AC86883CB03A8386 FOREIGN KEY (created_by_id) REFERENCES auth.users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analyses_microstratigraphic_units ADD CONSTRAINT FK_1A1A0B527941003F FOREIGN KEY (analysis_id) REFERENCES analyses (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analyses_microstratigraphic_units ADD CONSTRAINT FK_1A1A0B5223EDC87 FOREIGN KEY (subject_id) REFERENCES samples (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analysis_context_zoo_taxonomies ADD CONSTRAINT FK_87214BDC7941003F FOREIGN KEY (analysis_id) REFERENCES analysis_context_zoos (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analysis_context_zoo_taxonomies ADD CONSTRAINT FK_87214BDC9557E6F6 FOREIGN KEY (taxonomy_id) REFERENCES vocabulary.zoo_taxonomy (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analysis_context_zoos ADD CONSTRAINT FK_4CDE93227941003F FOREIGN KEY (analysis_id) REFERENCES analyses (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analysis_context_zoos ADD CONSTRAINT FK_4CDE932223EDC87 FOREIGN KEY (subject_id) REFERENCES contexts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analysis_potteries ADD CONSTRAINT FK_631A18587941003F FOREIGN KEY (analysis_id) REFERENCES analyses (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analysis_potteries ADD CONSTRAINT FK_631A185823EDC87 FOREIGN KEY (subject_id) REFERENCES potteries (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analysis_zoo_bones ADD CONSTRAINT FK_EB9AEAD07941003F FOREIGN KEY (analysis_id) REFERENCES analyses (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analysis_zoo_bones ADD CONSTRAINT FK_EB9AEAD023EDC87 FOREIGN KEY (subject_id) REFERENCES zoo_bones (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analysis_zoo_teeth ADD CONSTRAINT FK_BE6E6D8B7941003F FOREIGN KEY (analysis_id) REFERENCES analyses (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analysis_zoo_teeth ADD CONSTRAINT FK_BE6E6D8B23EDC87 FOREIGN KEY (subject_id) REFERENCES zoo_teeth (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE context_stratigraphic_units ADD CONSTRAINT FK_A2BE5B62BDB1218E FOREIGN KEY (su_id) REFERENCES sus (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE context_stratigraphic_units ADD CONSTRAINT FK_A2BE5B626B00C1CF FOREIGN KEY (context_id) REFERENCES contexts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contexts ADD CONSTRAINT FK_AC51CEB5C54C8C93 FOREIGN KEY (type_id) REFERENCES vocabulary.context_types (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contexts ADD CONSTRAINT FK_AC51CEB5F6BD1646 FOREIGN KEY (site_id) REFERENCES sites (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE individuals ADD CONSTRAINT FK_985AD930F6BD1646 FOREIGN KEY (site_id) REFERENCES sus (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE individuals ADD CONSTRAINT FK_985AD930CC80CD12 FOREIGN KEY (age_id) REFERENCES vocabulary.individual_ages (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_object_analyses ADD CONSTRAINT FK_C2D113064DE5A5 FOREIGN KEY (media_object_id) REFERENCES media_objects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_object_analyses ADD CONSTRAINT FK_C2D1130126F525E FOREIGN KEY (item_id) REFERENCES analyses (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_object_stratigraphic_units ADD CONSTRAINT FK_2DAB12CC64DE5A5 FOREIGN KEY (media_object_id) REFERENCES media_objects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_object_stratigraphic_units ADD CONSTRAINT FK_2DAB12CC126F525E FOREIGN KEY (item_id) REFERENCES sus (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_objects ADD CONSTRAINT FK_D3CD4ABAC54C8C93 FOREIGN KEY (type_id) REFERENCES vocabulary.media_object_types (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_objects ADD CONSTRAINT FK_D3CD4ABAA2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES auth.users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mus ADD CONSTRAINT FK_240A2C54A502ADE FOREIGN KEY (stratigraphic_unit_id) REFERENCES sus (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE potteries ADD CONSTRAINT FK_91910162A502ADE FOREIGN KEY (stratigraphic_unit_id) REFERENCES sus (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE potteries ADD CONSTRAINT FK_91910162EFB04BBB FOREIGN KEY (surface_treatment_id) REFERENCES vocabulary.surface_treatment (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE potteries ADD CONSTRAINT FK_9191016271C15152 FOREIGN KEY (cultural_context_id) REFERENCES vocabulary.cultural_contexts (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE potteries ADD CONSTRAINT FK_919101624CE34BEC FOREIGN KEY (part_id) REFERENCES vocabulary.pottery_shapes (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE potteries ADD CONSTRAINT FK_919101629D56156 FOREIGN KEY (functional_group_id) REFERENCES vocabulary.pottery_functional_groups (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE potteries ADD CONSTRAINT FK_91910162BC19D7E9 FOREIGN KEY (functional_form_id) REFERENCES vocabulary.pottery_functional_forms (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pottery_decorations ADD CONSTRAINT FK_9E9301E3F23816BB FOREIGN KEY (pottery_id) REFERENCES potteries (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pottery_decorations ADD CONSTRAINT FK_9E9301E33446DFC4 FOREIGN KEY (decoration_id) REFERENCES vocabulary.decoration (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sample_stratigraphic_units ADD CONSTRAINT FK_1A344B061B1FEA20 FOREIGN KEY (sample_id) REFERENCES samples (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sample_stratigraphic_units ADD CONSTRAINT FK_1A344B06BDB1218E FOREIGN KEY (su_id) REFERENCES sus (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE samples ADD CONSTRAINT FK_19925777F6BD1646 FOREIGN KEY (site_id) REFERENCES sites (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE samples ADD CONSTRAINT FK_19925777C54C8C93 FOREIGN KEY (type_id) REFERENCES vocabulary.sample_types (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE site_cultural_contexts ADD CONSTRAINT FK_35F57A8EF6BD1646 FOREIGN KEY (site_id) REFERENCES sites (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE site_cultural_contexts ADD CONSTRAINT FK_35F57A8E71C15152 FOREIGN KEY (cultural_context_id) REFERENCES vocabulary.cultural_contexts (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE auth.site_user_privileges ADD CONSTRAINT FK_7FEC3DADA76ED395 FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE auth.site_user_privileges ADD CONSTRAINT FK_7FEC3DADF6BD1646 FOREIGN KEY (site_id) REFERENCES sites (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sites ADD CONSTRAINT FK_BC00AA63B03A8386 FOREIGN KEY (created_by_id) REFERENCES auth.users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stratigraphic_units_relationships ADD CONSTRAINT FK_14B3FD8DD4B657AB FOREIGN KEY (lft_su_id) REFERENCES sus (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stratigraphic_units_relationships ADD CONSTRAINT FK_14B3FD8D2C41D668 FOREIGN KEY (relationship_id) REFERENCES vocabulary.su_relationships (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stratigraphic_units_relationships ADD CONSTRAINT FK_14B3FD8D7C1ECED6 FOREIGN KEY (rgt_su_id) REFERENCES sus (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vocabulary.su_relationships ADD CONSTRAINT FK_319E6DFFC4CDAD40 FOREIGN KEY (inverted_by_id) REFERENCES vocabulary.su_relationships (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sus ADD CONSTRAINT FK_32B2A22EF6BD1646 FOREIGN KEY (site_id) REFERENCES sites (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE zoo_bones ADD CONSTRAINT FK_1911F3EAA502ADE FOREIGN KEY (stratigraphic_unit_id) REFERENCES sus (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE zoo_bones ADD CONSTRAINT FK_1911F3EA2A3A1291 FOREIGN KEY (voc_taxonomy_id) REFERENCES vocabulary.zoo_taxonomy (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE zoo_bones ADD CONSTRAINT FK_1911F3EAE26518D6 FOREIGN KEY (voc_bone_id) REFERENCES vocabulary.zoo_bones (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE zoo_bones ADD CONSTRAINT FK_1911F3EA2BAA4AD9 FOREIGN KEY (voc_bone_part_id) REFERENCES vocabulary.zoo_bone_parts (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE zoo_teeth ADD CONSTRAINT FK_4CE574B1A502ADE FOREIGN KEY (stratigraphic_unit_id) REFERENCES sus (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE zoo_teeth ADD CONSTRAINT FK_4CE574B12A3A1291 FOREIGN KEY (voc_taxonomy_id) REFERENCES vocabulary.zoo_taxonomy (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE zoo_teeth ADD CONSTRAINT FK_4CE574B123332A79 FOREIGN KEY (voc_tooth_id) REFERENCES vocabulary.zoo_bones (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE analyses_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE analysis_join_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE analysis_context_zoo_taxonomies_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vocabulary.analysis_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE context_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vocabulary.context_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vocabulary.decoration_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE individuals_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE media_object_join_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vocabulary.media_object_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE media_objects_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE mus_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE potteries_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pottery_decorations_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vocabulary.pottery_functional_forms_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vocabulary.pottery_functional_groups_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vocabulary.pottery_shapes_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE sample_stratigraphic_units_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vocabulary.sample_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE site_cultural_contexts_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE stratigraphic_units_relationships_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vocabulary.surface_treatment_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vocabulary.zoo_bone_parts_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE zoo_bone_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vocabulary.zoo_bones_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vocabulary.zoo_taxonomy_id_seq CASCADE');
        $this->addSql('ALTER TABLE analyses DROP CONSTRAINT FK_AC86883CBF9DEA95');
        $this->addSql('ALTER TABLE analyses DROP CONSTRAINT FK_AC86883CB03A8386');
        $this->addSql('ALTER TABLE analyses_microstratigraphic_units DROP CONSTRAINT FK_1A1A0B527941003F');
        $this->addSql('ALTER TABLE analyses_microstratigraphic_units DROP CONSTRAINT FK_1A1A0B5223EDC87');
        $this->addSql('ALTER TABLE analysis_context_zoo_taxonomies DROP CONSTRAINT FK_87214BDC7941003F');
        $this->addSql('ALTER TABLE analysis_context_zoo_taxonomies DROP CONSTRAINT FK_87214BDC9557E6F6');
        $this->addSql('ALTER TABLE analysis_context_zoos DROP CONSTRAINT FK_4CDE93227941003F');
        $this->addSql('ALTER TABLE analysis_context_zoos DROP CONSTRAINT FK_4CDE932223EDC87');
        $this->addSql('ALTER TABLE analysis_potteries DROP CONSTRAINT FK_631A18587941003F');
        $this->addSql('ALTER TABLE analysis_potteries DROP CONSTRAINT FK_631A185823EDC87');
        $this->addSql('ALTER TABLE analysis_zoo_bones DROP CONSTRAINT FK_EB9AEAD07941003F');
        $this->addSql('ALTER TABLE analysis_zoo_bones DROP CONSTRAINT FK_EB9AEAD023EDC87');
        $this->addSql('ALTER TABLE analysis_zoo_teeth DROP CONSTRAINT FK_BE6E6D8B7941003F');
        $this->addSql('ALTER TABLE analysis_zoo_teeth DROP CONSTRAINT FK_BE6E6D8B23EDC87');
        $this->addSql('ALTER TABLE context_stratigraphic_units DROP CONSTRAINT FK_A2BE5B62BDB1218E');
        $this->addSql('ALTER TABLE context_stratigraphic_units DROP CONSTRAINT FK_A2BE5B626B00C1CF');
        $this->addSql('ALTER TABLE contexts DROP CONSTRAINT FK_AC51CEB5C54C8C93');
        $this->addSql('ALTER TABLE contexts DROP CONSTRAINT FK_AC51CEB5F6BD1646');
        $this->addSql('ALTER TABLE individuals DROP CONSTRAINT FK_985AD930F6BD1646');
        $this->addSql('ALTER TABLE individuals DROP CONSTRAINT FK_985AD930CC80CD12');
        $this->addSql('ALTER TABLE media_object_analyses DROP CONSTRAINT FK_C2D113064DE5A5');
        $this->addSql('ALTER TABLE media_object_analyses DROP CONSTRAINT FK_C2D1130126F525E');
        $this->addSql('ALTER TABLE media_object_stratigraphic_units DROP CONSTRAINT FK_2DAB12CC64DE5A5');
        $this->addSql('ALTER TABLE media_object_stratigraphic_units DROP CONSTRAINT FK_2DAB12CC126F525E');
        $this->addSql('ALTER TABLE media_objects DROP CONSTRAINT FK_D3CD4ABAC54C8C93');
        $this->addSql('ALTER TABLE media_objects DROP CONSTRAINT FK_D3CD4ABAA2B28FE8');
        $this->addSql('ALTER TABLE mus DROP CONSTRAINT FK_240A2C54A502ADE');
        $this->addSql('ALTER TABLE potteries DROP CONSTRAINT FK_91910162A502ADE');
        $this->addSql('ALTER TABLE potteries DROP CONSTRAINT FK_91910162EFB04BBB');
        $this->addSql('ALTER TABLE potteries DROP CONSTRAINT FK_9191016271C15152');
        $this->addSql('ALTER TABLE potteries DROP CONSTRAINT FK_919101624CE34BEC');
        $this->addSql('ALTER TABLE potteries DROP CONSTRAINT FK_919101629D56156');
        $this->addSql('ALTER TABLE potteries DROP CONSTRAINT FK_91910162BC19D7E9');
        $this->addSql('ALTER TABLE pottery_decorations DROP CONSTRAINT FK_9E9301E3F23816BB');
        $this->addSql('ALTER TABLE pottery_decorations DROP CONSTRAINT FK_9E9301E33446DFC4');
        $this->addSql('ALTER TABLE sample_stratigraphic_units DROP CONSTRAINT FK_1A344B061B1FEA20');
        $this->addSql('ALTER TABLE sample_stratigraphic_units DROP CONSTRAINT FK_1A344B06BDB1218E');
        $this->addSql('ALTER TABLE samples DROP CONSTRAINT FK_19925777F6BD1646');
        $this->addSql('ALTER TABLE samples DROP CONSTRAINT FK_19925777C54C8C93');
        $this->addSql('ALTER TABLE site_cultural_contexts DROP CONSTRAINT FK_35F57A8EF6BD1646');
        $this->addSql('ALTER TABLE site_cultural_contexts DROP CONSTRAINT FK_35F57A8E71C15152');
        $this->addSql('ALTER TABLE auth.site_user_privileges DROP CONSTRAINT FK_7FEC3DADA76ED395');
        $this->addSql('ALTER TABLE auth.site_user_privileges DROP CONSTRAINT FK_7FEC3DADF6BD1646');
        $this->addSql('ALTER TABLE sites DROP CONSTRAINT FK_BC00AA63B03A8386');
        $this->addSql('ALTER TABLE stratigraphic_units_relationships DROP CONSTRAINT FK_14B3FD8DD4B657AB');
        $this->addSql('ALTER TABLE stratigraphic_units_relationships DROP CONSTRAINT FK_14B3FD8D2C41D668');
        $this->addSql('ALTER TABLE stratigraphic_units_relationships DROP CONSTRAINT FK_14B3FD8D7C1ECED6');
        $this->addSql('ALTER TABLE vocabulary.su_relationships DROP CONSTRAINT FK_319E6DFFC4CDAD40');
        $this->addSql('ALTER TABLE sus DROP CONSTRAINT FK_32B2A22EF6BD1646');
        $this->addSql('ALTER TABLE zoo_bones DROP CONSTRAINT FK_1911F3EAA502ADE');
        $this->addSql('ALTER TABLE zoo_bones DROP CONSTRAINT FK_1911F3EA2A3A1291');
        $this->addSql('ALTER TABLE zoo_bones DROP CONSTRAINT FK_1911F3EAE26518D6');
        $this->addSql('ALTER TABLE zoo_bones DROP CONSTRAINT FK_1911F3EA2BAA4AD9');
        $this->addSql('ALTER TABLE zoo_teeth DROP CONSTRAINT FK_4CE574B1A502ADE');
        $this->addSql('ALTER TABLE zoo_teeth DROP CONSTRAINT FK_4CE574B12A3A1291');
        $this->addSql('ALTER TABLE zoo_teeth DROP CONSTRAINT FK_4CE574B123332A79');
        $this->addSql('DROP TABLE analyses');
        $this->addSql('DROP TABLE analyses_microstratigraphic_units');
        $this->addSql('DROP TABLE analysis_context_zoo_taxonomies');
        $this->addSql('DROP TABLE analysis_context_zoos');
        $this->addSql('DROP TABLE analysis_potteries');
        $this->addSql('DROP TABLE vocabulary.analysis_types');
        $this->addSql('DROP TABLE analysis_zoo_bones');
        $this->addSql('DROP TABLE analysis_zoo_teeth');
        $this->addSql('DROP TABLE context_stratigraphic_units');
        $this->addSql('DROP TABLE vocabulary.context_types');
        $this->addSql('DROP TABLE contexts');
        $this->addSql('DROP TABLE vocabulary.cultural_contexts');
        $this->addSql('DROP TABLE vocabulary.decoration');
        $this->addSql('DROP TABLE vocabulary.individual_ages');
        $this->addSql('DROP TABLE individuals');
        $this->addSql('DROP TABLE media_object_analyses');
        $this->addSql('DROP TABLE media_object_stratigraphic_units');
        $this->addSql('DROP TABLE vocabulary.media_object_types');
        $this->addSql('DROP TABLE media_objects');
        $this->addSql('DROP TABLE mus');
        $this->addSql('DROP TABLE potteries');
        $this->addSql('DROP TABLE pottery_decorations');
        $this->addSql('DROP TABLE vocabulary.pottery_functional_forms');
        $this->addSql('DROP TABLE vocabulary.pottery_functional_groups');
        $this->addSql('DROP TABLE vocabulary.pottery_shapes');
        $this->addSql('DROP TABLE auth.refresh_tokens');
        $this->addSql('DROP TABLE sample_stratigraphic_units');
        $this->addSql('DROP TABLE vocabulary.sample_types');
        $this->addSql('DROP TABLE samples');
        $this->addSql('DROP TABLE site_cultural_contexts');
        $this->addSql('DROP TABLE auth.site_user_privileges');
        $this->addSql('DROP TABLE sites');
        $this->addSql('DROP TABLE stratigraphic_units_relationships');
        $this->addSql('DROP TABLE vocabulary.su_relationships');
        $this->addSql('DROP TABLE vocabulary.surface_treatment');
        $this->addSql('DROP TABLE sus');
        $this->addSql('DROP TABLE auth.users');
        $this->addSql('DROP TABLE vocabulary.zoo_bone_parts');
        $this->addSql('DROP TABLE zoo_bones');
        $this->addSql('DROP TABLE vocabulary.zoo_bones');
        $this->addSql('DROP TABLE vocabulary.zoo_taxonomy');
        $this->addSql('DROP TABLE zoo_teeth');
    }
}
