<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250621090503 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA vocabulary');
        $this->addSql('CREATE SCHEMA auth');
        $this->addSql('CREATE SEQUENCE analyses_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE context_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vocabulary.sample_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE site_cultural_contexts_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE stratigraphic_units_relationships_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE analyses (id BIGINT NOT NULL, type SMALLINT NOT NULL, status SMALLINT NOT NULL, description TEXT DEFAULT NULL, su_id BIGINT NOT NULL, context_id BIGINT NOT NULL, sample_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC86883CBDB1218E ON analyses (su_id)');
        $this->addSql('CREATE INDEX IDX_AC86883C6B00C1CF ON analyses (context_id)');
        $this->addSql('CREATE INDEX IDX_AC86883C1B1FEA20 ON analyses (sample_id)');
        $this->addSql('CREATE TABLE context_stratigraphic_units (id BIGINT NOT NULL, su_id BIGINT NOT NULL, context_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A2BE5B62BDB1218E ON context_stratigraphic_units (su_id)');
        $this->addSql('CREATE INDEX IDX_A2BE5B626B00C1CF ON context_stratigraphic_units (context_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2BE5B62BDB1218E6B00C1CF ON context_stratigraphic_units (su_id, context_id)');
        $this->addSql('CREATE TABLE contexts (id BIGINT NOT NULL, type SMALLINT NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, site_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC51CEB5F6BD1646 ON contexts (site_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AC51CEB5F6BD16468CDE57295E237E06 ON contexts (site_id, type, name)');
        $this->addSql('CREATE TABLE vocabulary.cultural_contexts (id SMALLINT NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DC0C4A0E1D775834 ON vocabulary.cultural_contexts (value)');
        $this->addSql('CREATE TABLE auth.refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_39BB651DC74F2195 ON auth.refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE vocabulary.sample_types (id SMALLINT NOT NULL, code VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F19230977153098 ON vocabulary.sample_types (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F1923091D775834 ON vocabulary.sample_types (value)');
        $this->addSql('CREATE TABLE samples (id BIGINT NOT NULL, site_id BIGINT NOT NULL, year SMALLINT NOT NULL, number SMALLINT NOT NULL, description TEXT DEFAULT NULL, su_id BIGINT DEFAULT NULL, context_id BIGINT DEFAULT NULL, type_id SMALLINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_19925777BDB1218E ON samples (su_id)');
        $this->addSql('CREATE INDEX IDX_199257776B00C1CF ON samples (context_id)');
        $this->addSql('CREATE INDEX IDX_19925777C54C8C93 ON samples (type_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_19925777F6BD164696901F54 ON samples (site_id, number)');
        $this->addSql('CREATE TABLE site_cultural_contexts (id BIGINT NOT NULL, site_id BIGINT NOT NULL, cultural_context_id SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_35F57A8EF6BD1646 ON site_cultural_contexts (site_id)');
        $this->addSql('CREATE INDEX IDX_35F57A8E71C15152 ON site_cultural_contexts (cultural_context_id)');
        $this->addSql('CREATE TABLE auth.site_user_privileges (id UUID NOT NULL, privilege INT NOT NULL, user_id UUID NOT NULL, site_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7FEC3DADA76ED395 ON auth.site_user_privileges (user_id)');
        $this->addSql('CREATE INDEX IDX_7FEC3DADF6BD1646 ON auth.site_user_privileges (site_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7FEC3DADA76ED395F6BD1646 ON auth.site_user_privileges (user_id, site_id)');
        $this->addSql('CREATE TABLE sites (id BIGINT NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, chronology_lower SMALLINT DEFAULT NULL, chronology_upper SMALLINT DEFAULT NULL, field_director VARCHAR(255) DEFAULT NULL, created_by_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BC00AA6377153098 ON sites (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BC00AA635E237E06 ON sites (name)');
        $this->addSql('CREATE INDEX IDX_BC00AA63B03A8386 ON sites (created_by_id)');
        $this->addSql('CREATE TABLE stratigraphic_units_relationships (id BIGINT NOT NULL, lft_su_id BIGINT NOT NULL, relationship_id CHAR(1) NOT NULL, rgt_su_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_14B3FD8DD4B657AB ON stratigraphic_units_relationships (lft_su_id)');
        $this->addSql('CREATE INDEX IDX_14B3FD8D2C41D668 ON stratigraphic_units_relationships (relationship_id)');
        $this->addSql('CREATE INDEX IDX_14B3FD8D7C1ECED6 ON stratigraphic_units_relationships (rgt_su_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_14B3FD8DD4B657AB7C1ECED6 ON stratigraphic_units_relationships (lft_su_id, rgt_su_id)');
        $this->addSql('CREATE TABLE vocabulary.su_relationships (id CHAR(1) NOT NULL, value VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, inverted_by_id CHAR(1) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_319E6DFF1D775834 ON vocabulary.su_relationships (value)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_319E6DFFC4CDAD40 ON vocabulary.su_relationships (inverted_by_id)');
        $this->addSql('CREATE TABLE sus (id BIGINT NOT NULL, year INT NOT NULL, number INT NOT NULL, description TEXT DEFAULT NULL, interpretation TEXT DEFAULT NULL, site_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_32B2A22EF6BD1646 ON sus (site_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_32B2A22EF6BD1646BB82733796901F54 ON sus (site_id, year, number)');
        $this->addSql('CREATE TABLE auth.users (id UUID NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_18DF2AF8E7927C74 ON auth.users (email)');
        $this->addSql('ALTER TABLE analyses ADD CONSTRAINT FK_AC86883CBDB1218E FOREIGN KEY (su_id) REFERENCES sus (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analyses ADD CONSTRAINT FK_AC86883C6B00C1CF FOREIGN KEY (context_id) REFERENCES contexts (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analyses ADD CONSTRAINT FK_AC86883C1B1FEA20 FOREIGN KEY (sample_id) REFERENCES samples (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE context_stratigraphic_units ADD CONSTRAINT FK_A2BE5B62BDB1218E FOREIGN KEY (su_id) REFERENCES sus (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE context_stratigraphic_units ADD CONSTRAINT FK_A2BE5B626B00C1CF FOREIGN KEY (context_id) REFERENCES contexts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contexts ADD CONSTRAINT FK_AC51CEB5F6BD1646 FOREIGN KEY (site_id) REFERENCES sites (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE samples ADD CONSTRAINT FK_19925777BDB1218E FOREIGN KEY (su_id) REFERENCES sus (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE samples ADD CONSTRAINT FK_199257776B00C1CF FOREIGN KEY (context_id) REFERENCES contexts (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE samples ADD CONSTRAINT FK_19925777C54C8C93 FOREIGN KEY (type_id) REFERENCES vocabulary.sample_types (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE site_cultural_contexts ADD CONSTRAINT FK_35F57A8EF6BD1646 FOREIGN KEY (site_id) REFERENCES sites (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE site_cultural_contexts ADD CONSTRAINT FK_35F57A8E71C15152 FOREIGN KEY (cultural_context_id) REFERENCES vocabulary.cultural_contexts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE auth.site_user_privileges ADD CONSTRAINT FK_7FEC3DADA76ED395 FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE auth.site_user_privileges ADD CONSTRAINT FK_7FEC3DADF6BD1646 FOREIGN KEY (site_id) REFERENCES sites (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sites ADD CONSTRAINT FK_BC00AA63B03A8386 FOREIGN KEY (created_by_id) REFERENCES auth.users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stratigraphic_units_relationships ADD CONSTRAINT FK_14B3FD8DD4B657AB FOREIGN KEY (lft_su_id) REFERENCES sus (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stratigraphic_units_relationships ADD CONSTRAINT FK_14B3FD8D2C41D668 FOREIGN KEY (relationship_id) REFERENCES vocabulary.su_relationships (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stratigraphic_units_relationships ADD CONSTRAINT FK_14B3FD8D7C1ECED6 FOREIGN KEY (rgt_su_id) REFERENCES sus (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vocabulary.su_relationships ADD CONSTRAINT FK_319E6DFFC4CDAD40 FOREIGN KEY (inverted_by_id) REFERENCES vocabulary.su_relationships (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sus ADD CONSTRAINT FK_32B2A22EF6BD1646 FOREIGN KEY (site_id) REFERENCES sites (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE analyses_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE context_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vocabulary.sample_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE site_cultural_contexts_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE stratigraphic_units_relationships_id_seq CASCADE');
        $this->addSql('ALTER TABLE analyses DROP CONSTRAINT FK_AC86883CBDB1218E');
        $this->addSql('ALTER TABLE analyses DROP CONSTRAINT FK_AC86883C6B00C1CF');
        $this->addSql('ALTER TABLE analyses DROP CONSTRAINT FK_AC86883C1B1FEA20');
        $this->addSql('ALTER TABLE context_stratigraphic_units DROP CONSTRAINT FK_A2BE5B62BDB1218E');
        $this->addSql('ALTER TABLE context_stratigraphic_units DROP CONSTRAINT FK_A2BE5B626B00C1CF');
        $this->addSql('ALTER TABLE contexts DROP CONSTRAINT FK_AC51CEB5F6BD1646');
        $this->addSql('ALTER TABLE samples DROP CONSTRAINT FK_19925777BDB1218E');
        $this->addSql('ALTER TABLE samples DROP CONSTRAINT FK_199257776B00C1CF');
        $this->addSql('ALTER TABLE samples DROP CONSTRAINT FK_19925777C54C8C93');
        $this->addSql('ALTER TABLE site_cultural_contexts DROP CONSTRAINT FK_35F57A8EF6BD1646');
        $this->addSql('ALTER TABLE site_cultural_contexts DROP CONSTRAINT FK_35F57A8E71C15152');
        $this->addSql('ALTER TABLE auth.site_user_privileges DROP CONSTRAINT FK_7FEC3DADA76ED395');
        $this->addSql('ALTER TABLE auth.site_user_privileges DROP CONSTRAINT FK_7FEC3DADF6BD1646');
        $this->addSql('ALTER TABLE sites DROP CONSTRAINT FK_BC00AA63B03A8386');
        $this->addSql('ALTER TABLE stratigraphic_units_relationships DROP CONSTRAINT FK_14B3FD8DD4B657AB');
        $this->addSql('ALTER TABLE stratigraphic_units_relationships DROP CONSTRAINT FK_14B3FD8D2C41D668');
        $this->addSql('ALTER TABLE stratigraphic_units_relationships DROP CONSTRAINT FK_14B3FD8D7C1ECED6');
        $this->addSql('ALTER TABLE vocabulary.su_relationships DROP CONSTRAINT FK_319E6DFFC4CDAD40');
        $this->addSql('ALTER TABLE sus DROP CONSTRAINT FK_32B2A22EF6BD1646');
        $this->addSql('DROP TABLE analyses');
        $this->addSql('DROP TABLE context_stratigraphic_units');
        $this->addSql('DROP TABLE contexts');
        $this->addSql('DROP TABLE vocabulary.cultural_contexts');
        $this->addSql('DROP TABLE auth.refresh_tokens');
        $this->addSql('DROP TABLE vocabulary.sample_types');
        $this->addSql('DROP TABLE samples');
        $this->addSql('DROP TABLE site_cultural_contexts');
        $this->addSql('DROP TABLE auth.site_user_privileges');
        $this->addSql('DROP TABLE sites');
        $this->addSql('DROP TABLE stratigraphic_units_relationships');
        $this->addSql('DROP TABLE vocabulary.su_relationships');
        $this->addSql('DROP TABLE sus');
        $this->addSql('DROP TABLE auth.users');
    }
}
