<?php

namespace App\Doctrine\Filter;

use App\Entity\Data\MediaObject;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\Query\Filter\SQLFilter;

/**
 * Global SQL filter that enforces public-only access to MediaObject entities.
 *
 * This filter acts as a low-level "fail-safe" security layer. It is automatically
 * enabled by the PublicMediaFilterListener for all unauthenticated users at the
 * start of every request.
 *
 * Once enabled, it automatically appends 'AND public = true' to any SQL query
 * targeting the media_objects table, including:
 * 1. Direct queries via API Platform resources.
 * 2. Subqueries generated by complex API filters (e.g., search/exists on media properties).
 * 3. Joins from other entities where the Doctrine Extension might not be active.
 *
 * It works in tandem with the PublicMediaSecurityExtension, which handles the
 * higher-level cleanup of join records to prevent "orphaned" null relations in JSON.
 */
class PublicMediaObjectSqlFilter extends SQLFilter
{
    public function addFilterConstraint(ClassMetadata $targetEntity, $targetTableAlias): string
    {
        if (MediaObject::class !== $targetEntity->getName()) {
            return '';
        }

        return sprintf('%s.public = true', $targetTableAlias);
    }
}
